baseURL = "http://jmh1234.github.io/"
languageCode = "zh-Hans"
title = "jimh的博客"
theme="dream"

#copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-98295641-1"

disqusShortname = "jimh"

enableRobotsTXT = true

hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # background = "black"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "小叽"
  description = "我的学习记录"
  avatar = "/me/yy.jpg"
  motto = "前路漫漫，为剑所伴。"
  categoriesLimitInHeader = 6

  rss = true

  utterancesRepo = "jmh1234.github.io-creator/jmh1234.github.io"

  email = "923268677@qq.com"
  github = "jmh1234"
#  twitter = "jimh"
#  facebook = "jimh"
#  instagram = "jimh"
#  linkedin = "jimh"
#  stackoverflow = "5676489/g1eny0ung"
#  codepen = "jimh"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  highlightjs = true
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true
